spring:
  application:
    name: portfolio-manager
  
  datasource:
    url: jdbc:postgresql://localhost:5433/finsight_db
    username: user
    password: mi_super_password_segura
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  data:
    redis:
      host: localhost
      port: 6379
      password: mi_redis_pass_seguro

  grpc:
    client:
      local-grpc-server:
        address: 'static://localhost:50051'
        negotiation-type: plaintext

  jwt:
    secret: "pon_un_secreto_largo_64+_chars"
    issuer: "finsight"
    access-expiration-ms: 3600000
    refresh-expiration-ms: 604800000